刘茜： 作业一单元测试
cloud-itp-xiaomi/training_2024 pull request #112
Opened 2024-06-11 10:36 UTC by gigilx

单元测试

2024-06-12 01:38 UTC, maqianli2024 commented on liuxi/UtilizationCollectionSystem/server/src/test/java/com/lx/server/pojo/ResUtilizationTest.java
> +
多余的空行

2024-06-12 01:38 UTC, maqianli2024 commented on liuxi/UtilizationCollectionSystem/server/src/test/java/com/lx/server/service/UtilizationServiceTest.java
> +
多余的空行

2024-06-12 01:38 UTC, maqianli2024 commented on liuxi/UtilizationCollectionSystem/server/src/main/java/com/lx/server/dao/RedisDao.java
> +    private ValueOperations<String, Object> operations ;
最后面多了空格

2024-06-12 07:33 UTC, maqianli2024 requested changes
多余的空格、空行处理一下

2024-06-12 12:42 UTC, gigilx commented
老师，函数之间不能有空行吗





------------------&nbsp;原始邮件&nbsp;------------------
发件人:                                                                                                                        "cloud-itp-xiaomi/training_2024"                                                                                    ***@***.***&gt;;
发送时间:&nbsp;2024年6月12日(星期三) 上午9:38
***@***.***&gt;;
***@***.******@***.***&gt;;
主题:&nbsp;Re: [cloud-itp-xiaomi/training_2024] 刘茜： 作业一单元测试 (PR #112)





 
@maqianli2024 commented on this pull request.
 
 
In liuxi/UtilizationCollectionSystem/server/src/test/java/com/lx/server/service/UtilizationServiceTest.java:
 &gt; +        ResUtilization[] res = utilizationService.getData(utilizationList); +        for(ResUtilization resUtilization : res){ +            System.out.println(resUtilization); +        } +    } + +    public Utilization getUtilization() { +        Utilization utilization = new Utilization(); +        utilization.setEndpoint("095dc3f39ca1"); +        utilization.setMetric("mem.used.percent"); +        utilization.setTimestamp(606013640L); +        utilization.setStep(60L); +        utilization.setValue(81.5); +        return utilization; +    } +  
多余的空行
 
—
Reply to this email directly, view it on GitHub, or unsubscribe.
You are receiving this because you authored the thread.Message ID: ***@***.***&gt;

2024-06-12 12:45 UTC, gigilx commented
@maqianli2024 作业二collector模块初步完成

2024-06-13 06:12 UTC, maqianli2024 commented
> 老师，函数之间不能有空行吗
> […](#)
> ------------------&nbsp;原始邮件&nbsp;------------------ 发件人: "cloud-itp-xiaomi/training_2024" ***@***.***&gt;; 发送时间:&nbsp;2024年6月12日(星期三) 上午9:38 ***@***.***&gt;; ***@***.******@***.***&gt;; 主题:&nbsp;Re: [cloud-itp-xiaomi/training_2024] 刘茜： 作业一单元测试 (PR #112) @maqianli2024 commented on this pull request. In liuxi/UtilizationCollectionSystem/server/src/test/java/com/lx/server/service/UtilizationServiceTest.java: &gt; + ResUtilization[] res = utilizationService.getData(utilizationList); + for(ResUtilization resUtilization : res){ + System.out.println(resUtilization); + } + } + + public Utilization getUtilization() { + Utilization utilization = new Utilization(); + utilization.setEndpoint("095dc3f39ca1"); + utilization.setMetric("mem.used.percent"); + utilization.setTimestamp(606013640L); + utilization.setStep(60L); + utilization.setValue(81.5); + return utilization; + } + 多余的空行 — Reply to this email directly, view it on GitHub, or unsubscribe. You are receiving this because you authored the thread.Message ID: ***@***.***&gt;

可以的。也应该的。一行就够了。

2024-06-13 06:13 UTC, gigilx commented
好的




------------------&nbsp;原始邮件&nbsp;------------------
发件人: ***@***.***&gt;; 
发送时间: 2024年6月13日(星期四) 下午2:13
收件人: ***@***.***&gt;; 
抄送: ***@***.***&gt;; ***@***.***&gt;; 
主题: Re: [cloud-itp-xiaomi/training_2024] 刘茜： 作业一单元测试 (PR #112)














  
老师，函数之间不能有空行吗
 …
 ------------------&nbsp;原始邮件&nbsp;------------------ 发件人: "cloud-itp-xiaomi/training_2024" @.&gt;; 发送时间:&nbsp;2024年6月12日(星期三) 上午9:38 @.&gt;; @.@.&gt;; 主题:&nbsp;Re: [cloud-itp-xiaomi/training_2024] 刘茜： 作业一单元测试 (PR #112) @maqianli2024 commented on this pull request. In liuxi/UtilizationCollectionSystem/server/src/test/java/com/lx/server/service/UtilizationServiceTest.java: &gt; + ResUtilization[] res = utilizationService.getData(utilizationList); + for(ResUtilization resUtilization : res){ + System.out.println(resUtilization); + } + } + + public Utilization getUtilization() { + Utilization utilization = new Utilization(); + utilization.setEndpoint("095dc3f39ca1"); + utilization.setMetric("mem.used.percent"); + utilization.setTimestamp(606013640L); + utilization.setStep(60L); + utilization.setValue(81.5); + return utilization; + } + 多余的空行 — Reply to this email directly, view it on GitHub, or unsubscribe. You are receiving this because you authored the thread.Message ID: @.***&gt;
  
可以的。也应该的。一行就够了。
 
—
Reply to this email directly, view it on GitHub, or unsubscribe.
You are receiving this because you authored the thread.Message ID: ***@***.***&gt;

2024-06-13 07:18 UTC, maqianli2024 commented on liuxi/LogCollect/collector/src/main/java/com/lx/collector/service/impl/CollectServiceImpl.java
> +        if(!cpuFields[0].equals("cpu"))
条件判断语句，即使只有一行，也用花括号

2024-06-13 07:19 UTC, maqianli2024 commented on liuxi/LogCollect/collector/src/main/java/com/lx/collector/service/impl/CollectServiceImpl.java
> +
多余的空行

2024-06-13 07:20 UTC, maqianli2024 approved these changes

2024-06-13 07:20 UTC, merged