Collector的初步实现
cloud-itp-xiaomi/training_2024 pull request #63
Opened 2024-05-29 14:05 UTC by windsky5901

Collector的初步实现，获取centos7的cpu情况

2024-05-30 01:50 UTC, maqianli2024 requested changes
更新 .gitignore，不要提交 .idea 文件 @windsky5901

2024-05-30 03:49 UTC, maqianli2024 commented
标题格式改一下，“杨翰林：Collector的初步实现”。方便导师筛选自己团队学员的 PR。

2024-05-30 04:36 UTC, pengmq1 commented
see

2024-06-11 06:46 UTC, maqianli2024 commented
@pengmq1 review 完导师合并。

2024-06-14 06:55 UTC, pengmq1 commented
取消跟踪.idea目录下的文件
使用`git rm –cached 文件名`命令取消跟踪某个文件
然后再提交一个commit就行了

2024-06-17 04:13 UTC, closed without merging